heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

resources:
  haproxy:
    type: OS::Nova::Server
    properties:
      image: haproxy
      flavor: m2.small
  cassandra:
    type: OS::Nova::Server
    properties:
      image: cassandra
      flavor: m2.small
  apache-zookeeper:
    type: OS::Nova::Server
    properties:
      image: jplock/zookeeper
      flavor: m2.small
  apache-activemq:
    type: OS::Nova::Server
    properties:
      image: webcenter/activemq
      flavor: m2.small
  tomcat:
    type: OS::Nova::Server
    properties:
      image: tomcat
      flavor: m2.small
  apache-spark:
    type: OS::Nova::Server
    properties:
      image: sequenceiq/spark
      flavor: m2.small
  memcached:
    type: OS::Nova::Server
    properties:
      image: memcached
      flavor: m2.small
  redis:
    type: OS::Nova::Server
    properties:
      image: redis
      flavor: m2.small
  solr:
    type: OS::Nova::Server
    properties:
      image: solr
      flavor: m2.small
  mysql:
    type: OS::Nova::Server
    properties:
      image: mysql
      flavor: m2.small
