heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

resources:
  activemq:
    type: OS::Nova::Server
    properties:
      image: bxavier/activemq-import
      flavor: m2.small
  haproxy:
    type: OS::Nova::Server
    properties:
      image: bxavier/haproxy-import
      flavor: m2.small
  memcached:
    type: OS::Nova::Server
    properties:
      image: bxavier/memcached-import
      flavor: m2.small
  redis:
    type: OS::Nova::Server
    properties:
      image: bxavier/redis-import
      flavor: m2.small
  tomcat:
    type: OS::Nova::Server
    properties:
      image: bxavier/tomcat-import
      flavor: m2.small
