heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

resources:
  unikernel01:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/unikernel01
      flavor: m1.small
  unikernel02:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/unikernel02
      flavor: m2.small
  unikernel03:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/unikernel03
      flavor: m2.small
  unikernel04:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/unikernel04
      flavor: m2.small
  unikernel05:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/unikernel05
      flavor: m2.small
  unikernel06:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/unikernel06
      flavor: m2.small
  unikernel07:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/unikernel07
      flavor: m2.small
  unikernel08:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/unikernel08
      flavor: m2.small
  unikernel09:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/unikernel09
      flavor: m2.small
  unikernel10:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/unikernel10
      flavor: m2.small
