heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

resources:
  haproxy:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/haproxy
      flavor: m2.small
  memcached:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/memcached
      flavor: m2.small
  redis-memonly:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/redis-memonly
      flavor: m2.small
  mysql41:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/mysql41
      flavor: m2.small
  node:
    type: OS::Nova::Server
    properties:
      image: git@10.32.45.217:/opt/git/node
      flavor: m2.small
